### ISSUE TITLE
Command definitions

### ISSUE THREAD

**Issue by SvartaHjarta** [HRingurinn/Rubot#17]
The current way commands are defined is to say the least a bit silly, having to define each command in two places is double the work.

I've looked into some alternatives and found a total of three ways:

1. The current double defining way
2. The [macros](https://github.com/serenity-rs/serenity/blob/current/examples/e05_command_framework/src/main.rs) defined in `serenity::framework::standard::macros`
3. [Poise](https://github.com/ev3nvy/poise/tree/current/examples/feature_showcase) a command framework for Serenity

**Comment by samuelhafsteins** [comment]
I have looked more into this and I've seen good recommendations for Poise. I'm thinking about creating on PR with it to test it's qualities.
